[model]
type = "FluxPipeline"
# pretrained_model_name_or_path = "black-forest-labs/FLUX.1-dev"
pretrained_model_name_or_path = "/home/ailab/model_weights/flux/FLUX.1-dev/"
torch_dtype = "bf16"

[hook]
type = "FluxVisAttentionHook"
vis_cross_attn = true
vis_self_attn = false
save_dir = "flux_cross_attention_outputs/"
hook_trans_block = true
hook_single_trans_block = false
max_sequence_length = 512
height = 1024
width = 1024

[execute]
prompts = [
    "An astronaut riding a horse on mars, 4K, photorealistic, sharp focus, best quality",
]
target_token = [
    ["astronaut", "horse", "mars"],
]

[execute.model]
height = 1024
width = 1024
guidance_scale = 3.5
num_inference_steps = 50
max_sequence_length = 512

[execute.hook]
apply_heat_map = true
renorm = true
